name: O Phoenix
favicon: null
layout_spectrum: 0.31200223369523883
typography_spectrum: 0.5089427190832794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.30379398236982524
  lightness: 0.4238003846257925
  saturation: 0.1544473310932517
  rhythmicContrast: 0.5652951532974839
purpose: []
